Assorted fixes
LDanielMedinaC/eduapp-backend pull request #36
Opened 2019-11-02 21:42 UTC by Syul968

Casing, tests, ids...

2019-12-02 16:51 UTC, RComonfort commented
Please fix conflicts in order to review :3

2019-12-05 03:24 UTC, DarkHaliax96 commented on server/middleware/validations/tutoring-validation.js
> +        return ErrorFactory.buildError(Errors.INVALId_ID, 'tutorId', tutoring.tutorId);
Is this ok?

2019-12-05 04:31 UTC, Syul968 commented on server/middleware/validations/tutoring-validation.js
> +        return ErrorFactory.buildError(Errors.INVALId_ID, 'tutorId', tutoring.tutorId);
No.

2019-12-05 04:42 UTC, AngelRRuizM approved these changes

2019-12-05 05:13 UTC, RComonfort requested changes

2019-12-05 05:13 UTC, RComonfort commented on server/models/user.js
> +            workExperiences: {
Where is the workExperience model?

2019-12-05 05:15 UTC, RComonfort commented
Also, need to solve conflicts still

2019-12-05 05:35 UTC, Syul968 commented on server/models/user.js
> +            workExperiences: {
In `sprint3` 😃

2019-12-05 05:43 UTC, RComonfort approved these changes

2019-12-05 05:43 UTC, RComonfort commented
Now thats more like it

2019-12-05 05:43 UTC, merged